[build]
  command = "npm install && bash ./netlify-build.sh && npm run build"
  functions = "netlify/functions"
  publish = "public"
  environment = { NODE_VERSION = "18" }

# Removing plugin to avoid Node.js version conflicts

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "utils/**", "models/**", "controllers/**", "routes/**", "docs/**"]

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
